jira:
  properties:
    password: admin
    username: admin
    worklogs-url-template: http://localhost:8080/rest/tempo-timesheets/3/worklogs?dateFrom={dateFrom}&dateTo={dateTo}
spring:
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/worklog-reminder}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: none