jira:
  basic-auth:
    username: ${JIRA_BASIC_USER}
    password: ${JIRA_BASIC_PASS}
  form-auth:
    username: ${JIRA_FROM_USER}
    password: ${JIRA_FORM_PASS}
  worklogs-url-template: ${JIRA_HOST:https://localhost:8080}/rest/tempo-timesheets/3/worklogs?dateFrom={dateFrom}&dateTo={dateTo}
  login-url: ${JIRA_HOST:https://localhost:8080}/login.jsp
spring:
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/worklog-reminder}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: none
server:
  port: 8100
