server:
  port: ${SERVER_PORT:8300}

spring:
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5434/employee}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: none
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}

rabbitmq:
  region:
    exchange: ${RABBITMQ_REGION_EXCHANGE:region.exchange}
    queue:
      created: ${RABBITMQ_REGION_CREATED_QUEUE:employee.region.created.queue}
      updated: ${RABBITMQ_REGION_UPDATED_QUEUE:employee.region.updated.queue}
      deleted: ${RABBITMQ_REGION_DELETED_QUEUE:employee.region.deleted.queue}
    max-retries: 3
    backoff-multiplier: 2
    max-backoff-ms: 10000
    initial-backoff-ms: 1000

notification:
  rest:
    api:
      base-url: ${NOTIFICATION_BASE_URL:http://localhost:8200}
      get-users-by-logins-uri: ${NOTIFICATION_BASE_URL:http://localhost:8200}/api/users?logins={logins}
      update-user-uri: ${NOTIFICATION_BASE_URL:http://localhost:8200}/api/users
      delete-user-by-login-uri: ${NOTIFICATION_BASE_URL:http://localhost:8200}/api/users/{id}

rest-template:
  read-timeout-seconds: 5
  connection-timeout-seconds: 5

springdoc:
  api-docs:
    path: /api/docs/services/employee
  swagger-ui:
    disable-swagger-default-url: true
    path: /api/docs/services/employee/swagger-ui

logging:
  level:
    com.senla.worklog.reminder.employee: trace
    com.senla.worklog.reminder.exception: trace
