jira:
  basic-auth:
    username: ${JIRA_BASIC_USER}
    password: ${JIRA_BASIC_PASS}
  form-auth:
    username: ${JIRA_FORM_USER}
    password: ${JIRA_FORM_PASS}
  debug:
    password-enabled: ${JIRA_DEBUG_PASSWORD_ENABLED:false}
  base-url: ${JIRA_BASE_URL}
  login-url: ${JIRA_BASE_URL}/login.jsp
  rest:
    api:
      v4:
        get-worklogs-uri: ${JIRA_BASE_URL}/rest/tempo-timesheets/4/worklogs/search
server:
  port: 8100

employee:
  rest:
    api:
      base-url: ${EMPLOYEE_BASE_URL:http://localhost:8300}
      get-employee-by-jira-key-uri: ${EMPLOYEE_BASE_URL:http://localhost:8300}/api/employees?jiraKey={jiraKey}

logging:
  level:
    com.senla.worklog.reminder.worklogdebt: trace
    com.senla.worklog.reminder.exception: trace
