jira:
  basic-auth:
    username: ${JIRA_BASIC_USER}
    password: ${JIRA_BASIC_PASS}
  form-auth:
    username: ${JIRA_FORM_USER}
    password: ${JIRA_FORM_PASS}
  login-url: ${JIRA_HOST:http://localhost:8080}/login.jsp
  debug:
    password-enabled: ${JIRA_DEBUG_PASSWORD_ENABLED:false}
  host: ${JIRA_HOST:http://localhost:8080}
notification:
  host: ${NOTIFICATION_HOST:http://localhost:8200}
spring:
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/worklog-debts}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: none
server:
  port: 8100

logging:
  level:
    com.senla.worklog.reminder: debug
