logging:
  level:
    com.senla.worklog.reminder.apigateway: debug

spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "${CORS_ALLOWED_ORIGIN_PATTERNS:*}"
            allowedMethods: "${CORS_ALLOWED_METHODS:GET,POST,PUT,DELETE,PATCH}"
            allowedHeaders: "${CORS_ALLOWED_HEADERS:*}"
            maxAge: "${CORS_MAX_AGE:3600}"
