logging:
  level:
    com.senla.worklog.reminder.apigateway: debug
cors:
  allowedOrigins: ${CORS_ALLOWED_ORIGINS}
  allowedMethods: ${CORS_ALLOWED_METHODS}
  allowedHeaders: ${CORS_ALLOWED_HEADERS}
  maxAge: ${CORS_MAXAGE}
