version: '3.8'

services:
  worklog-debt:
    image: letimof/worklog-debt:0.0.1
    container_name: worklog-debt
    mem_reservation: 700m
    pull_policy: always
    expose:
      - '8100'
    networks:
      - worklog-reminder-network
    environment:
      SERVER_PORT: 8100
      JIRA_BASE_URL: ${JIRA_BASE_URL}
      JIRA_BASIC_USER: ${JIRA_BASIC_USER}
      JIRA_BASIC_PASS: ${JIRA_BASIC_PASS}
      JIRA_FORM_USER: ${JIRA_FORM_USER}
      JIRA_FORM_PASS: ${JIRA_FORM_PASS}
      JIRA_DEBUG_PASSWORD_ENABLED: ${JIRA_DEBUG_PASSWORD_ENABLED:-false}
      EMPLOYEE_BASE_URL: http://employee:8300

  worklog-debt-notification:
    image: letimof/worklog-debt-notification:0.0.1
    container_name: worklog-debt-notification
    pull_policy: always
    expose:
      - '8400'
    networks:
      - worklog-reminder-network
    environment:
      SERVER_PORT: 8400
      NOTIFICATION_BASE_URL: http://notification:8200
      WORKLOGDEBT_BASE_URL: http://worklog-debt:8100

  employee:
    image: letimof/employee:0.0.1
    container_name: employee
    mem_reservation: 700m
    pull_policy: always
    expose:
      - '8300'
    networks:
      - worklog-reminder-network
    depends_on:
      - employee-db
    environment:
      SERVER_PORT: 8300
      NOTIFICATION_BASE_URL: http://notification:8200
      SPRING_DATASOURCE_URL: jdbc:postgresql://employee-db:5434/${EMPLOYEE_DB:-employee}
      SPRING_DATASOURCE_USERNAME: ${EMPLOYEE_DB_USER:-postgres}
      SPRING_DATASOURCE_PASSWORD: ${EMPLOYEE_DB_PASS:-postgres}
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME:-guest}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD:-guest}
      RABBITMQ_REGION_EXCHANGE: region.exchange
      RABBITMQ_REGION_CREATED_QUEUE: employee.region.created.queue
      RABBITMQ_REGION_UPDATED_QUEUE: employee.region.updated.queue
      RABBITMQ_REGION_DELETED_QUEUE: employee.region.deleted.queue
  employee-db:
    image: 'postgres:14.4'
    container_name: employee-db
    ports:
      - '5434:5434'
    networks:
      - worklog-reminder-network
    environment:
      POSTGRES_DB: ${EMPLOYEE_DB:-employee}
      POSTGRES_USER: ${EMPLOYEE_DB_USER:-postgres}
      POSTGRES_PASSWORD: ${EMPLOYEE_DB_PASS:-postgres}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./employee-db:/var/lib/postgresql/data
    command: -p 5434

  notification:
    image: letimof/notification:0.0.1
    container_name: notification
    mem_reservation: 700m
    pull_policy: always
    ports:
      - '8200:8200'
    networks:
      - worklog-reminder-network
    depends_on:
      - notification-db
    environment:
      MICROSOFT_APP_ID: ${MICROSOFT_APP_ID}
      MICROSOFT_APP_PASSWORD: ${MICROSOFT_APP_PASSWORD}
      MICROSOFT_APP_TYPE: ${MICROSOFT_APP_TYPE}
      POSTGRES_DB: ${NOTIFICATION_DB}
      POSTGRES_USER: ${NOTIFICATION_DB_USER}
      POSTGRES_PASSWORD: ${NOTIFICATION_DB_PASS}
      POSTGRES_HOST: notification-db
      POSTGRES_PORT: 5433
  notification-db:
    image: 'postgres:14.4'
    container_name: notification-db
    expose:
      - '5433'
    networks:
      - worklog-reminder-network
    environment:
      POSTGRES_DB: ${NOTIFICATION_DB:-notification}
      POSTGRES_USER: ${NOTIFICATION_DB_USER:-postgres}
      POSTGRES_PASSWORD: ${NOTIFICATION_DB_PASS:-postgres}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./notification-db:/var/lib/postgresql/data
    command: -p 5433

  region:
    image: letimof/region:0.0.1
    container_name: region
    mem_reservation: 700m
    pull_policy: always
    expose:
      - '8500'
    networks:
      - worklog-reminder-network
    depends_on:
      - region-db
      - rabbitmq
    environment:
      SERVER_PORT: 8500
      SPRING_DATASOURCE_URL: jdbc:postgresql://region-db:5435/${REGION_DB:-region}
      SPRING_DATASOURCE_USERNAME: ${REGION_DB_USER:-postgres}
      SPRING_DATASOURCE_PASSWORD: ${REGION_DB_PASS:-postgres}
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME:-guest}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD:-guest}
      RABBITMQ_REGION_EXCHANGE: region.exchange
  region-db:
    image: 'postgres:14.4'
    container_name: region-db
    expose:
      - '5435'
    networks:
      - worklog-reminder-network
    environment:
      POSTGRES_DB: ${REGION_DB:-region}
      POSTGRES_USER: ${REGION_DB_USER:-postgres}
      POSTGRES_PASSWORD: ${REGION_DB_PASS:-postgres}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./region-db:/var/lib/postgresql/data
    command: -p 5435

  frontend:
    image: letimof/frontend:0.0.1
    container_name: frontend
    pull_policy: always
    ports:
      - '3000:3000'
    networks:
      - worklog-reminder-network

  api-gateway:
    image: letimof/api-gateway:0.0.1
    container_name: api-gateway
    pull_policy: always
    ports:
      - '8080:8080'
    networks:
      - worklog-reminder-network
    environment:
      SPRING_CLOUD_GATEWAY_ROUTES_0_ID: worklog-debt-routes
      SPRING_CLOUD_GATEWAY_ROUTES_0_URI: http://worklog-debt:8100
      SPRING_CLOUD_GATEWAY_ROUTES_0_PREDICATES_0: Path=/api/worklog-debts/**
      SPRING_CLOUD_GATEWAY_ROUTES_0_FILTERS_0: AddRequestHeader=Host, worklog-debt

      SPRING_CLOUD_GATEWAY_ROUTES_1_ID: worklog-debt-notification-routes
      SPRING_CLOUD_GATEWAY_ROUTES_1_URI: http://worklog-debt-notification:8400
      SPRING_CLOUD_GATEWAY_ROUTES_1_PREDICATES_0: Path=/api/worklog-debts-notifications/**
      SPRING_CLOUD_GATEWAY_ROUTES_1_FILTERS_0: AddRequestHeader=Host, worklog-debt-notification

      SPRING_CLOUD_GATEWAY_ROUTES_2_ID: employee-routes
      SPRING_CLOUD_GATEWAY_ROUTES_2_URI: http://employee:8300
      SPRING_CLOUD_GATEWAY_ROUTES_2_PREDICATES_0: Path=/api/employees/**
      SPRING_CLOUD_GATEWAY_ROUTES_2_FILTERS_0: AddRequestHeader=Host, employee

      SPRING_CLOUD_GATEWAY_ROUTES_3_ID: notification-routes
      SPRING_CLOUD_GATEWAY_ROUTES_3_URI: http://notification:8200
      SPRING_CLOUD_GATEWAY_ROUTES_3_PREDICATES_0: Path=/api/bot/**, /api/notifications/**, /api/users/**
      SPRING_CLOUD_GATEWAY_ROUTES_3_FILTERS_0: AddRequestHeader=Host, notification

      SPRING_CLOUD_GATEWAY_ROUTES_4_ID: region-routes
      SPRING_CLOUD_GATEWAY_ROUTES_4_URI: http://region:8500
      SPRING_CLOUD_GATEWAY_ROUTES_4_PREDICATES_0: Path=/api/regions/**
      SPRING_CLOUD_GATEWAY_ROUTES_4_FILTERS_0: AddRequestHeader=Host, region
    depends_on:
      - worklog-debt
      - worklog-debt-notification
      - employee
      - notification

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - worklog-reminder-network
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD:-guest}

networks:
  worklog-reminder-network:
    driver: bridge
