version: '3.8'

services:
  worklog-reminder:
    image: letimof/worklog-reminder:0.0.1-SNAPSHOT
    mem_reservation: 700m
    ports:
      - "8100:8100"
    networks:
      - worklog-reminder-network
    depends_on:
      - postgres
    environment:
      JIRA_HOST: ${JIRA_HOST}
      JIRA_USER: ${JIRA_USER}
      JIRA_PASS: ${JIRA_PASS}
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB:-worklog-reminder}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER:-postgres}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASS:-postgres}
  postgres:
    image: 'postgres:14.4'
    container_name: worklog-reminder-database
    ports:
      - "5432:5432"
    expose:
      - 5432
    networks:
      - worklog-reminder-network
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-worklog-reminder}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASS:-postgres}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - .:/var/lib/postgresql/data

networks:
  worklog-reminder-network:
    driver: bridge
