version: '3.8'

services:
  postgres:
    image: 'postgres:14.4'
    container_name: worklog-reminder-database
    ports:
      - "5432:5432"
    expose:
      - 5432
    networks:
      - internal-network
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-worklog-reminder}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASS:-postgres}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - .:/var/lib/postgresql/data

networks:
  internal-network:
    driver: bridge
