version: '3.8'

services:
  worklog-debts:
    image: letimof/worklog-debts:0.0.2-SNAPSHOT
    container_name: worklog-debts
    mem_reservation: 700m
    pull_policy: always
    ports:
      - "8100:8100"
    networks:
      - worklog-reminder-network
    depends_on:
      - worklog-debts-db
    environment:
      JIRA_HOST: ${JIRA_HOST}
      JIRA_BASIC_USER: ${JIRA_BASIC_USER}
      JIRA_BASIC_PASS: ${JIRA_BASIC_PASS}
      JIRA_FORM_USER: ${JIRA_FORM_USER}
      JIRA_FORM_PASS: ${JIRA_FORM_PASS}
      JIRA_DEBUG_PASSWORD_ENABLED: ${JIRA_DEBUG_PASSWORD_ENABLED:-false}
      SPRING_DATASOURCE_URL: jdbc:postgresql://worklog-debts-db:5432/${WORKLOG_DEBTS_DB:-worklog-debts}
      SPRING_DATASOURCE_USERNAME: ${WORKLOG_DEBTS_DB_USER:-postgres}
      SPRING_DATASOURCE_PASSWORD: ${WORKLOG_DEBTS_DB_PASS:-postgres}
  worklog-debts-db:
    image: 'postgres:14.4'
    container_name: worklog-debts-db
    ports:
      - "5432:5432"
    networks:
      - worklog-reminder-network
    environment:
      - POSTGRES_DB=${WORKLOG_DEBTS_DB:-worklog-debts}
      - POSTGRES_USER=${WORKLOG_DEBTS_DB_USER:-postgres}
      - POSTGRES_PASSWORD=${WORKLOG_DEBTS_DB_PASS:-postgres}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./worklog-debts-db:/var/lib/postgresql/data
  notification-db:
    image: 'postgres:14.4'
    container_name: notification-db
    ports:
      - "5433:5433"
    networks:
      - worklog-reminder-network
    environment:
      - POSTGRES_DB=${NOTIFICATION_DB:-notification}
      - POSTGRES_USER=${NOTIFICATION_DB_USER:-postgres}
      - POSTGRES_PASSWORD=${NOTIFICATION_DB_PASS:-postgres}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./notification-db:/var/lib/postgresql/data
    command: -p 5433

networks:
  worklog-reminder-network:
    driver: bridge
