spring:
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5435/region}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}

rabbitmq:
  region:
    exchange: ${RABBITMQ_REGION_EXCHANGE:exchange}
    queue:
      created: ${RABBITMQ_REGION_CREATED_QUEUE:region.created.queue}
      updated: ${RABBITMQ_REGION_UPDATED_QUEUE:region.updated.queue}
      deleted: ${RABBITMQ_REGION_DELETED_QUEUE:region.deleted.queue}

logging:
  level:
    com:
      senla:
        worklog:
          reminder:
            region: debug
