spring:
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5435/region}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
