name: Build CI

on:
  pull_request:
    branches:
      - master
      - dev
  workflow_dispatch:

jobs:
  build-commons-spring-boot-starter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build and Publish to Maven Local
        run: |
          cd services/commons-spring-boot-starter
          ./gradlew build
          ./gradlew publishToMavenLocal

      - uses: actions/upload-artifact@master
        with:
          name: commons-spring-boot-starter
          path: ~/.m2/repository/com/senla/worklog/reminder/commons-spring-boot-starter

  build-api-gateway:
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'corretto'

      - name: Checkout project sources
        uses: actions/checkout@v2

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Run build with Gradle Wrapper
        run: |-
          cd services/api-gateway
          ./gradlew build

      - name: Build and push Docker Image
        run: |-
          cd services/api-gateway
          ./gradlew pushDockerImage

  build-employee:
    needs: build-commons-spring-boot-starter
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'corretto'

      - name: Checkout project sources
        uses: actions/checkout@v2

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Download commons-spring-boot-starter
        uses: actions/download-artifact@master
        with:
          name: commons-spring-boot-starter
          path: ~/.m2/repository/com/senla/worklog/reminder/commons-spring-boot-starter

      - name: Run build with Gradle Wrapper
        run: |-
          cd services/employee
          ./gradlew build -PmavenLocalRepo=$HOME/.m2/repository

      - name: Build and push Docker Image
        run: |-
          cd services/employee
          ./gradlew pushDockerImage

  build-worklog-debts:
    needs: build-commons-spring-boot-starter
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'corretto'

      - name: Checkout project sources
        uses: actions/checkout@v2

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Download commons-spring-boot-starter
        uses: actions/download-artifact@master
        with:
          name: commons-spring-boot-starter
          path: ~/.m2/repository/com/senla/worklog/reminder/commons-spring-boot-starter

      - name: Run build with Gradle Wrapper
        run: |-
          cd services/worklog-debt
          ./gradlew build

      - name: Build and push Docker Image
        run: |-
          cd services/worklog-debt
          ./gradlew pushDockerImage

  build-worklog-debt-notification:
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'corretto'

      - name: Checkout project sources
        uses: actions/checkout@v2

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Run build with Gradle Wrapper
        run: |-
          cd services/worklog-debt-notification
          ./gradlew build

      - name: Build and push Docker Image
        run: |-
          cd services/worklog-debt-notification
          ./gradlew pushDockerImage

  build-region:
    needs: build-commons-spring-boot-starter
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'corretto'

      - name: Checkout project sources
        uses: actions/checkout@v2

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Download commons-spring-boot-starter
        uses: actions/download-artifact@master
        with:
          name: commons-spring-boot-starter
          path: ~/.m2/repository/com/senla/worklog/reminder/commons-spring-boot-starter

      - name: Run build with Gradle Wrapper
        run: |-
          cd services/region
          ./gradlew build

      - name: Build and push Docker Image
        run: |-
          cd services/region
          ./gradlew pushDockerImage

  build-frontend:
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: |-
          cd services/frontend
          npm install

      - name: Build and push Docker Image
        run: |-
          cd services/frontend
          npm run docker:build
          npm run docker:login
          npm run docker:push
