name: Notification Service CI

on:
  pull_request:
    branches:
      - master
      - dev
      - 0.0.3-SNAPSHOT
  workflow_dispatch:

jobs:
  build:
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: |-
          cd services/notification
          npm install

      - name: Run build if present
        run: |-
          cd services/notification 
          npm run build --if-present

      - name: Run tests
        run: |-
          cd services/notification
          npm test

      - name: Build and push Docker Image
        run: |-
          cd services/notification
          npm run docker:build
          npm run docker:login
          npm run docker:push
