name: WorklogDebtNotification Build CI

on:
  pull_request:
    branches:
      - master
      - dev
  workflow_dispatch:

jobs:
  build:
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'corretto'

      - name: Checkout project sources
        uses: actions/checkout@v2

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Run build with Gradle Wrapper
        run: |-
          cd services/worklog-debt-notification
          ./gradlew build

      - name: Build and push Docker Image
        run: |-
          cd services/worklog-debt-notification
          ./gradlew pushDockerImage
